package ru.saransklife.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ru.saransklife.dao.CacheInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CACHE_INFO.
*/
public class CacheInfoDao extends AbstractDao<CacheInfo, String> {

    public static final String TABLENAME = "CACHE_INFO";

    /**
     * Properties of entity CacheInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Request = new Property(0, String.class, "request", true, "REQUEST");
        public final static Property Last_updated = new Property(1, java.util.Date.class, "last_updated", false, "LAST_UPDATED");
    };


    public CacheInfoDao(DaoConfig config) {
        super(config);
    }
    
    public CacheInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CACHE_INFO' (" + //
                "'REQUEST' TEXT PRIMARY KEY NOT NULL ," + // 0: request
                "'LAST_UPDATED' INTEGER);"); // 1: last_updated
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CACHE_INFO'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, CacheInfo entity) {
        stmt.clearBindings();
 
        String request = entity.getRequest();
        if (request != null) {
            stmt.bindString(1, request);
        }
 
        java.util.Date last_updated = entity.getLast_updated();
        if (last_updated != null) {
            stmt.bindLong(2, last_updated.getTime());
        }
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public CacheInfo readEntity(Cursor cursor, int offset) {
        CacheInfo entity = new CacheInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // request
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)) // last_updated
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, CacheInfo entity, int offset) {
        entity.setRequest(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setLast_updated(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(CacheInfo entity, long rowId) {
        return entity.getRequest();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(CacheInfo entity) {
        if(entity != null) {
            return entity.getRequest();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
