package ru.saransklife.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE_INFO.
 */
public class CacheInfo {

    private String request;
    private java.util.Date last_updated;

    public CacheInfo() {
    }

    public CacheInfo(String request) {
        this.request = request;
    }

    public CacheInfo(String request, java.util.Date last_updated) {
        this.request = request;
        this.last_updated = last_updated;
    }

    public String getRequest() {
        return request;
    }

    public void setRequest(String request) {
        this.request = request;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

}
