package ru.saransklife.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CACHE_INFO.
 */
public class CacheInfo {

    private Long id;
    private String request;
    private String params;
    private java.util.Date last_updated;

    public CacheInfo() {
    }

    public CacheInfo(Long id) {
        this.id = id;
    }

    public CacheInfo(Long id, String request, String params, java.util.Date last_updated) {
        this.id = id;
        this.request = request;
        this.params = params;
        this.last_updated = last_updated;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getRequest() {
        return request;
    }

    public void setRequest(String request) {
        this.request = request;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public java.util.Date getLast_updated() {
        return last_updated;
    }

    public void setLast_updated(java.util.Date last_updated) {
        this.last_updated = last_updated;
    }

}
