package ru.saransklife.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ru.saransklife.dao.MenuItem;

import ru.saransklife.dao.MenuItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig menuItemDaoConfig;

    private final MenuItemDao menuItemDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        menuItemDaoConfig = daoConfigMap.get(MenuItemDao.class).clone();
        menuItemDaoConfig.initIdentityScope(type);

        menuItemDao = new MenuItemDao(menuItemDaoConfig, this);

        registerDao(MenuItem.class, menuItemDao);
    }
    
    public void clear() {
        menuItemDaoConfig.getIdentityScope().clear();
    }

    public MenuItemDao getMenuItemDao() {
        return menuItemDao;
    }

}
