package ru.saransklife.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table PAGE.
 */
public class PageDao extends AbstractDao<Page, Long> {

	public static final String TABLENAME = "PAGE";

	/**
	 * Properties of entity Page.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
		public final static Property Text = new Property(2, String.class, "text", false, "TEXT");
		public final static Property Slug = new Property(3, String.class, "slug", false, "SLUG");
	}

	;


	public PageDao(DaoConfig config) {
		super(config);
	}

	public PageDao(DaoConfig config, DaoSession daoSession) {
		super(config, daoSession);
	}

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'PAGE' (" + //
				"'_id' INTEGER PRIMARY KEY ," + // 0: id
				"'TITLE' TEXT," + // 1: title
				"'TEXT' TEXT," + // 2: text
				"'SLUG' TEXT UNIQUE );"); // 3: slug
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PAGE'";
		db.execSQL(sql);
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected void bindValues(SQLiteStatement stmt, Page entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String title = entity.getTitle();
		if (title != null) {
			stmt.bindString(2, title);
		}

		String text = entity.getText();
		if (text != null) {
			stmt.bindString(3, text);
		}

		String slug = entity.getSlug();
		if (slug != null) {
			stmt.bindString(4, slug);
		}
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Page readEntity(Cursor cursor, int offset) {
		Page entity = new Page( //
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
				cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // text
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // slug
		);
		return entity;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public void readEntity(Cursor cursor, Page entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
		entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
		entity.setText(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
		entity.setSlug(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected Long updateKeyAfterInsert(Page entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Long getKey(Page entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

}
