package ru.saransklife.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PAGE.
 */
public class Page {

    private Long id;
    private String title;
    private String text;
    private String slug;

    public Page() {
    }

    public Page(Long id) {
        this.id = id;
    }

    public Page(Long id, String title, String text, String slug) {
        this.id = id;
        this.title = title;
        this.text = text;
        this.slug = slug;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

}
