package ru.saransklife.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PLACE_CATEGORY.
 */
public class PlaceCategory {

    private Long id;
    private String name;
    private String slug;
    private String parent_slug;

    public PlaceCategory() {
    }

    public PlaceCategory(Long id) {
        this.id = id;
    }

    public PlaceCategory(Long id, String name, String slug, String parent_slug) {
        this.id = id;
        this.name = name;
        this.slug = slug;
        this.parent_slug = parent_slug;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSlug() {
        return slug;
    }

    public void setSlug(String slug) {
        this.slug = slug;
    }

    public String getParent_slug() {
        return parent_slug;
    }

    public void setParent_slug(String parent_slug) {
        this.parent_slug = parent_slug;
    }

}
