package ru.saransklife.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import ru.saransklife.dao.PlaceEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table PLACE_ENTITY.
*/
public class PlaceEntityDao extends AbstractDao<PlaceEntity, Long> {

    public static final String TABLENAME = "PLACE_ENTITY";

    /**
     * Properties of entity PlaceEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Address = new Property(2, String.class, "address", false, "ADDRESS");
        public final static Property Phone = new Property(3, String.class, "phone", false, "PHONE");
        public final static Property Email = new Property(4, String.class, "email", false, "EMAIL");
        public final static Property Website = new Property(5, String.class, "website", false, "WEBSITE");
        public final static Property Latitude = new Property(6, Float.class, "latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(7, Float.class, "longitude", false, "LONGITUDE");
        public final static Property Description = new Property(8, String.class, "description", false, "DESCRIPTION");
        public final static Property Photo_author = new Property(9, String.class, "photo_author", false, "PHOTO_AUTHOR");
        public final static Property Photo_path = new Property(10, String.class, "photo_path", false, "PHOTO_PATH");
        public final static Property Information = new Property(11, String.class, "information", false, "INFORMATION");
        public final static Property Working_time = new Property(12, String.class, "working_time", false, "WORKING_TIME");
        public final static Property Rating = new Property(13, Float.class, "rating", false, "RATING");
        public final static Property View_count = new Property(14, Integer.class, "view_count", false, "VIEW_COUNT");
        public final static Property Recommended_count = new Property(15, Integer.class, "recommended_count", false, "RECOMMENDED_COUNT");
    };


    public PlaceEntityDao(DaoConfig config) {
        super(config);
    }
    
    public PlaceEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'PLACE_ENTITY' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NAME' TEXT," + // 1: name
                "'ADDRESS' TEXT," + // 2: address
                "'PHONE' TEXT," + // 3: phone
                "'EMAIL' TEXT," + // 4: email
                "'WEBSITE' TEXT," + // 5: website
                "'LATITUDE' REAL," + // 6: latitude
                "'LONGITUDE' REAL," + // 7: longitude
                "'DESCRIPTION' TEXT," + // 8: description
                "'PHOTO_AUTHOR' TEXT," + // 9: photo_author
                "'PHOTO_PATH' TEXT," + // 10: photo_path
                "'INFORMATION' TEXT," + // 11: information
                "'WORKING_TIME' TEXT," + // 12: working_time
                "'RATING' REAL," + // 13: rating
                "'VIEW_COUNT' INTEGER," + // 14: view_count
                "'RECOMMENDED_COUNT' INTEGER);"); // 15: recommended_count
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'PLACE_ENTITY'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, PlaceEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String address = entity.getAddress();
        if (address != null) {
            stmt.bindString(3, address);
        }
 
        String phone = entity.getPhone();
        if (phone != null) {
            stmt.bindString(4, phone);
        }
 
        String email = entity.getEmail();
        if (email != null) {
            stmt.bindString(5, email);
        }
 
        String website = entity.getWebsite();
        if (website != null) {
            stmt.bindString(6, website);
        }
 
        Float latitude = entity.getLatitude();
        if (latitude != null) {
            stmt.bindDouble(7, latitude);
        }
 
        Float longitude = entity.getLongitude();
        if (longitude != null) {
            stmt.bindDouble(8, longitude);
        }
 
        String description = entity.getDescription();
        if (description != null) {
            stmt.bindString(9, description);
        }
 
        String photo_author = entity.getPhoto_author();
        if (photo_author != null) {
            stmt.bindString(10, photo_author);
        }
 
        String photo_path = entity.getPhoto_path();
        if (photo_path != null) {
            stmt.bindString(11, photo_path);
        }
 
        String information = entity.getInformation();
        if (information != null) {
            stmt.bindString(12, information);
        }
 
        String working_time = entity.getWorking_time();
        if (working_time != null) {
            stmt.bindString(13, working_time);
        }
 
        Float rating = entity.getRating();
        if (rating != null) {
            stmt.bindDouble(14, rating);
        }
 
        Integer view_count = entity.getView_count();
        if (view_count != null) {
            stmt.bindLong(15, view_count);
        }
 
        Integer recommended_count = entity.getRecommended_count();
        if (recommended_count != null) {
            stmt.bindLong(16, recommended_count);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public PlaceEntity readEntity(Cursor cursor, int offset) {
        PlaceEntity entity = new PlaceEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // address
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // phone
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // email
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // website
            cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6), // latitude
            cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7), // longitude
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // description
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // photo_author
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // photo_path
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // information
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // working_time
            cursor.isNull(offset + 13) ? null : cursor.getFloat(offset + 13), // rating
            cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14), // view_count
            cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15) // recommended_count
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, PlaceEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAddress(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhone(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setEmail(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setWebsite(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setLatitude(cursor.isNull(offset + 6) ? null : cursor.getFloat(offset + 6));
        entity.setLongitude(cursor.isNull(offset + 7) ? null : cursor.getFloat(offset + 7));
        entity.setDescription(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setPhoto_author(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setPhoto_path(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setInformation(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setWorking_time(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setRating(cursor.isNull(offset + 13) ? null : cursor.getFloat(offset + 13));
        entity.setView_count(cursor.isNull(offset + 14) ? null : cursor.getInt(offset + 14));
        entity.setRecommended_count(cursor.isNull(offset + 15) ? null : cursor.getInt(offset + 15));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(PlaceEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(PlaceEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
