package ru.saransklife.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table REFERENCE.
 */
public class ReferenceDao extends AbstractDao<Reference, Long> {

	public static final String TABLENAME = "REFERENCE";

	/**
	 * Properties of entity Reference.<br/>
	 * Can be used for QueryBuilder and for referencing column names.
	 */
	public static class Properties {
		public final static Property Id = new Property(0, Long.class, "id", true, "_id");
		public final static Property Slug = new Property(1, String.class, "slug", false, "SLUG");
		public final static Property Name = new Property(2, String.class, "name", false, "NAME");
		public final static Property Description = new Property(3, String.class, "description", false, "DESCRIPTION");
		public final static Property Phone = new Property(4, String.class, "phone", false, "PHONE");
		public final static Property Information = new Property(5, String.class, "information", false, "INFORMATION");
		public final static Property Address = new Property(6, String.class, "address", false, "ADDRESS");
		public final static Property Site = new Property(7, String.class, "site", false, "SITE");
	}

	;


	public ReferenceDao(DaoConfig config) {
		super(config);
	}

	public ReferenceDao(DaoConfig config, DaoSession daoSession) {
		super(config, daoSession);
	}

	/**
	 * Creates the underlying database table.
	 */
	public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
		String constraint = ifNotExists ? "IF NOT EXISTS " : "";
		db.execSQL("CREATE TABLE " + constraint + "'REFERENCE' (" + //
				"'_id' INTEGER PRIMARY KEY ," + // 0: id
				"'SLUG' TEXT," + // 1: slug
				"'NAME' TEXT," + // 2: name
				"'DESCRIPTION' TEXT," + // 3: description
				"'PHONE' TEXT," + // 4: phone
				"'INFORMATION' TEXT," + // 5: information
				"'ADDRESS' TEXT," + // 6: address
				"'SITE' TEXT);"); // 7: site
	}

	/**
	 * Drops the underlying database table.
	 */
	public static void dropTable(SQLiteDatabase db, boolean ifExists) {
		String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'REFERENCE'";
		db.execSQL(sql);
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected void bindValues(SQLiteStatement stmt, Reference entity) {
		stmt.clearBindings();

		Long id = entity.getId();
		if (id != null) {
			stmt.bindLong(1, id);
		}

		String slug = entity.getSlug();
		if (slug != null) {
			stmt.bindString(2, slug);
		}

		String name = entity.getName();
		if (name != null) {
			stmt.bindString(3, name);
		}

		String description = entity.getDescription();
		if (description != null) {
			stmt.bindString(4, description);
		}

		String phone = entity.getPhone();
		if (phone != null) {
			stmt.bindString(5, phone);
		}

		String information = entity.getInformation();
		if (information != null) {
			stmt.bindString(6, information);
		}

		String address = entity.getAddress();
		if (address != null) {
			stmt.bindString(7, address);
		}

		String site = entity.getSite();
		if (site != null) {
			stmt.bindString(8, site);
		}
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Long readKey(Cursor cursor, int offset) {
		return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Reference readEntity(Cursor cursor, int offset) {
		Reference entity = new Reference( //
				cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
				cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // slug
				cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
				cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // description
				cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // phone
				cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // information
				cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // address
				cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7) // site
		);
		return entity;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public void readEntity(Cursor cursor, Reference entity, int offset) {
		entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
		entity.setSlug(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
		entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
		entity.setDescription(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
		entity.setPhone(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
		entity.setInformation(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
		entity.setAddress(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
		entity.setSite(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected Long updateKeyAfterInsert(Reference entity, long rowId) {
		entity.setId(rowId);
		return rowId;
	}

	/**
	 * @inheritdoc
	 */
	@Override
	public Long getKey(Reference entity) {
		if (entity != null) {
			return entity.getId();
		} else {
			return null;
		}
	}

	/**
	 * @inheritdoc
	 */
	@Override
	protected boolean isEntityUpdateable() {
		return true;
	}

}
