package ru.saransklife.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table REFERENCE.
 */
public class Reference {

	private Long id;
	private String slug;
	private String name;
	private String description;
	private String phone;
	private String information;
	private String address;
	private String site;

	public Reference() {
	}

	public Reference(Long id) {
		this.id = id;
	}

	public Reference(Long id, String slug, String name, String description, String phone, String information, String address, String site) {
		this.id = id;
		this.slug = slug;
		this.name = name;
		this.description = description;
		this.phone = phone;
		this.information = information;
		this.address = address;
		this.site = site;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getInformation() {
		return information;
	}

	public void setInformation(String information) {
		this.information = information;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getSite() {
		return site;
	}

	public void setSite(String site) {
		this.site = site;
	}

}
