package ru.saransklife.client.event;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table EVENT_CATEGORY.
 */
public class EventCategory {

	private Long id;
	private String name;
	private String slug;

	public EventCategory() {
	}

	public EventCategory(Long id) {
		this.id = id;
	}

	public EventCategory(Long id, String name, String slug) {
		this.id = id;
		this.name = name;
		this.slug = slug;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSlug() {
		return slug;
	}

	public void setSlug(String slug) {
		this.slug = slug;
	}

}
